import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

import Hero from "@/components/Hero";

import Popular from "@/components/Popular";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    //  data-theme="light"
>
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        <Hero></Hero>
  
        <Popular></Popular>
        <main>

          {children}
        </main>
        
        </body>
    </html>
  );
}
